#!/bin/sh

config_file="/etc/config/samba4"
init_file="/etc/init.d/samba4"

case "$ACTION" in
	add)
		sleep 2
		for disk in $(ls /mnt | grep "sd[a-z][1-9]")
		do
			if ! grep -q "autoshare '1'" $config_file
			then
				exit
			elif ! grep -q "$disk" $config_file
			then
				echo -e "\n\nconfig sambashare" >> $config_file
				echo -e "\toption auto '1'" >> $config_file
				echo -e "\toption name '$disk'" >> $config_file
				echo -e "\toption path '/mnt/$disk'" >> $config_file
				echo -e "\toption read_only 'no'" >> $config_file
				echo -e "\toption force_root '1'" >> $config_file
				echo -e "\toption guest_ok 'yes'" >> $config_file
				echo -e "\toption create_mask '0777'" >> $config_file
				echo -e "\toption dir_mask '0777'" >> $config_file
				echo -e "\toption device '$disk'" >> $config_file
				echo -e "\toption inherit_owner 'yes'" >> $config_file
				$init_file reload
			fi
		done
		;;

	remove)
		i=0
		while true
		do
			if ! grep -q "auto '1'" $config_file
			then
				exit
			else
				disk=$(uci get samba4.@sambashare[$i].device)
				if [ ! -e "/mnt/$disk" ]
				then
					uci delete samba4.@sambashare[$i]
					uci commit
					$init_file reload
					return
				fi
			fi
			let i+=1
		done
		;;
esac