#!/bin/sh

cpu_arch="$(cat "/proc/cpuinfo" | grep "model name" | sed -n "1p" | awk -F ': ' '{print $2}')"
[ -z "${cpu_arch}" ] && cpu_arch="ARMv8 Processor"
cpu_cores="$(cat "/proc/cpuinfo" | grep "processor" | wc -l)"

if grep -q "bcm27xx" "/etc/openwrt_release"; then
	cpu_freq="$(expr $(vcgencmd measure_clock arm | awk -F '=' '{print $2}') / 1000000)Mhz"
elif grep -q "bcm53xx" "/etc/openwrt_release"; then
	cpu_freq="$(nvram get clkfreq | awk -F ',' '{print $1}')MHz"
elif grep -q "mvebu" "/etc/openwrt_release"; then
	cpu_freq="$(cat "/proc/cpuinfo" | grep "BogoMIPS" | sed -n "1p" | awk -F ': ' '{print $2}')MHz"
elif ! grep -q "filogic" "/etc/openwrt_release"; then
	cpu_freq="$(expr $(cat /sys/devices/system/cpu/cpufreq/policy0/cpuinfo_cur_freq) / 1000)MHz"
    if grep -q "rockchip" "/etc/openwrt_release"; then
	big_cpu_freq="$(expr $(cat /sys/devices/system/cpu/cpufreq/policy4/cpuinfo_cur_freq 2>"/dev/null") / 1000 2>"/dev/null")"
	[ -n "${big_cpu_freq}" ] && big_cpu_freq="${big_cpu_freq}MHz "
    fi
fi

if grep -q "ipq" "/etc/openwrt_release"; then
	if grep -q "ipq40xx" "/etc/openwrt_release"; then
		sys_temp="$(awk '{ printf("%.1f°C ", $0 / 1000) }' /sys/class/ieee80211/phy*/device/hwmon/hwmon*/temp1_input)"
	else
		sys_temp="$(awk '{ printf("%.1f°C ", $0 / 1000) }' /sys/class/thermal/thermal_zone0/temp)"
	fi
	echo -n "${cpu_arch} x ${cpu_cores} (${cpu_freq}, ${sys_temp})"
else
	if grep -q "bcm27xx" "/etc/openwrt_release"; then
		cpu_temp="$(vcgencmd measure_temp | awk -F '=' '{print $2}' | awk -F "'" '{print $1}')°C"
	else
		cpu_temp="$(awk "BEGIN{printf (\"%.1f\n\",$(cat /sys/class/thermal/thermal_zone0/temp)/1000) }")°C"
	fi
	if grep -q "filogic" "/etc/openwrt_release"; then
		wifi_temp0="$(awk '{ printf("%.1f°C", $0 / 1000) }' /sys/class/ieee80211/phy0/hwmon1/temp1_input)"
		wifi_temp1="$(awk '{ printf("%.1f°C", $0 / 1000) }' /sys/class/ieee80211/phy1/hwmon2/temp1_input)"
		echo -n "${cpu_arch} x ${cpu_cores} (CPU:${cpu_temp}, WIFI-2.4G:${wifi_temp0}, WIFI-5G:${wifi_temp1})"
	else
		echo -n "${cpu_arch} x ${cpu_cores} (${big_cpu_freq}${cpu_freq}, ${cpu_temp})"
	fi
fi
